### ISSUE TITLE
Can't get it to work using new Slack App token

### ISSUE THREAD

**Issue by frakman1** [benjifs/bitbar-slack-team-notifications#1] opened 2019-07-03 16:50 UTC
I have a slack app token (not `Legacy` because they are deprecated and channel admins are not granting them anymore due to the fact that they have too large a scope) I tried using it with this plugin and I get this error: `team.info: missing_scope`

I am guessing that there are some scope parameters that I need to be granted first. Can you please tell me what those are so I can request them from my admin? Ideally, I would get alll required scopes so I don't have to keep going back to them and requesting a change.

See [this](https://api.slack.com/docs/oauth-scopes) page for list of al available scopes

Thank you,

**Comment by frakman1** [comment] 2019-07-03 18:49
I have requested what I think are the right scope permissions based on the code but I still get the same error. Here are my app token scope permissions.

Is there any chance you can re-write your plugin with app tokens in mind? Legacy tokens are not allowed at my organization because their scope is deemed to be too large.

![image](https://user-images.githubusercontent.com/5826484/60617351-906f0080-9da1-11e9-9083-e3cb72d98eb9.png)

**Comment by benjifs** [comment] 2019-07-04 07:50
From my testing you'll need the following Slack OAuth scopes.
<img width="578" alt="Screen Shot 2019-07-04 at 2 42 55 AM" src="https://user-images.githubusercontent.com/4167938/60648409-7f57db00-9e05-11e9-8d2e-1ab5841b9486.png">

Dont forget that you then have to take the `code` from the Redirect URI after approving your app and call the following to generate the final token.

`https://slack.com/api/oauth.access?client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&code={CODE}`

You should then be able to copy the token generated from that and paste it in the `.tokens.js` file. Give that a shot and let me know if it works for you. I can work on adding OAuth here as well but since it mostly happens externally, I might just add the instructions if they work for you and leave it at that.

**Comment by frakman1** [comment] 2019-07-08 16:24
Thanks for the screenshot!

Before adding your scopes, my scope changes were approved and I tried them and got this error: `users.conversations: missing_scope`. I see where it is constructed here in your code:

```
		url = SLACK_CONVERSATIONS;
		debug('Fetch conversation info for ' + channel.id);
	}
	return slack_request(url + SLACK_INFO, {

```
How come your list of scopes doesn't include this `conversations.info` scope?

Also, why would I need to call anything to generate a final token? I thought I could use the one from the App's `Oath & Permissions` page. This is what mine looks like:

![image](https://user-images.githubusercontent.com/5826484/60825818-8753aa00-a17a-11e9-8f40-9072029adf35.png)


Finally, and sorry for asking if this is obvious, but where do I find this " `code` from the Redirect URI". I don't really use a redirect URL since I don't distribute this app. It's just used internally.

**Comment by frakman1** [comment] 2019-07-08 18:06
OK. So I added the missing scopes from your list, got re-approved, and refreshed the slack plugin script and now it gets a bit farther. It shows some unread messages in a channel but throws another error:
![image](https://user-images.githubusercontent.com/5826484/60832304-8c6c2580-a189-11e9-8a5a-dec8a1eadef3.png)

**Comment by benjifs** [comment] 2019-07-09 05:17
> How come your list of scopes doesn't include this `conversations.info` scope?

It seems that the other permissions that are shown in the screenshot handle that specific call. You can read more about it here: https://api.slack.com/methods/conversations.info
 
> Also, why would I need to call anything to generate a final token? I thought I could use the one from the App's `Oath & Permissions` page. 

You are correct. I was unaware that you could install the app you created from that same workspace. There is no need to make the call to generate the final token if you do it this way.

> Finally, and sorry for asking if this is obvious, but where do I find this " `code` from the Redirect URI". I don't really use a redirect URL since I don't distribute this app. It's just used internally.

Same as above. No need to handle that code as you can manually install it from the app settings page.

> OK. So I added the missing scopes from your list, got re-approved, and refreshed the slack plugin script and now it gets a bit farther. It shows some unread messages in a channel but throws another error:
> ![image](https://user-images.githubusercontent.com/5826484/60832304-8c6c2580-a189-11e9-8a5a-dec8a1eadef3.png)

From the [documentation](https://api.slack.com/methods/channels.info) about `channels.info` that error should happen if the ID passed is not a valid channel. I actually have not seen that happen so that's very interesting but maybe we can figure it out somehow. If you can, try calling the script directly from the terminal.
```./slack-team-notifications.1m.js --debug```
That should tell you for which channel the call is failing. Hopefully from there we can figure out what the issue is.

**Comment by frakman1** [comment] 2019-07-09 06:12
Thank you for taking the time to explain so thoroughly. I ran the command with the `--debug` flag and withheld a bunch of user-specific information from the output below:

```
$./slack-team-notifications.1m.js --debug
Debugging
Fetching channels for xoxp-xxxxx
  /team.info
  /users.conversations
Fetch channel info for #... (...)
  /channels.info (...)
Fetch channel info for #... (...)
  /channels.info (...)
Fetch channel info for #... (...)
  /channels.info (...)
Fetch channel info for #... (...)
  /channels.info (...)
Fetch channel info for #... (...)
  /channels.info (...)
Fetch channel info for #... (...)
  /channels.info (...)
Fetch channel info for #... (...)
  /channels.info (...)
Fetch channel info for #... (...)
  /channels.info #... (...)
Fetch channel info for #... (...)
  /channels.info (...)
Fetch channel info for #... (...)
  /channels.info (...)
Fetch group info for #... (...)
  /groups.info (...)
Fetch group info for #... (...)
  /groups.info (...)
Fetch group info for #... (...)
  /groups.info (...)
Fetch group info for #... (...)
  /groups.info (...)
Fetch group info for #... (...)
  /groups.info (...)
Fetch group info for #... (...)
  /groups.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
Fetch conversation info for ...
  /conversations.info (...)
 | image=iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAWJQAAFiUBSVIk8AAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAABLNJREFUWAmllstvTVEUxg9Vr1BVYYBIDJpIGGAibdN2RoIwYCBG5R/pjZAwYoSJQRO0BgYMqKQdVycqIpHcDkx1QpXE+/H9ztnftXvt++yXfGevs/baa6+91jr73ixrjFWRyajksvhOnBIHRLBa7MilLOvXyBw22JZEI/ZlXcujnYxr5Z8EhyOPQ4l51kwEG/uKlrQm+tTHtAzH38Wf4m/xi4huVjSQ0TGHDbasQYcPsKYY0k9SXQ8+EWUwCBL9uqDYp7E7EBkwh40PhO4ID8E+i7eqZ91oI9vPQeak1Yj7J3VAB+Ax5aPiM+WgMimBtINHIo7Wii7bj6D7FUYNK0czAZH2snghbEdQZJaRU28RXRpnQar2EJcMGYeplLL5mPhKPCf2iDQs9jTwJ7FLTK2VOgkO4YSwDn/5SX2qXIGyDuY0B1PYJqVLnJqPdQRDqaGRx0FWfKqjkvvEzqBzoHqtgBNBgiewh6KBn9Qaz3tkPX3YK54WN4kz4jOxgnFJOGyVk1qzMXjZrfFj8EGm7MvNPxrsGEZEz3v05ZmVwiQLiZyxGX4L625rBHvEegFdyq2y7JBGB4EP74uuJGbzIi+UwYbNjLZf0DrKvENcCj5SGbqsOXBNxP/XMCITFGOZevJ1AORWYPv1WkQf2GktH2wI+EKBr4pY7sLpazSCS8DCevTpsQdvxQ+ByIDS44OvCHvwshgqX5b9YGdfeSz9UqBslyfCRgzHa/h5GtnQc+wVB+S9iSXHoJ7PRZqSSw7y+8WILiZ9wjsndjBk2iUkKK4EbOivW+IG0bgugQDIqv2z95CY3xu+pHjnV7u6tr6XvCnNSL/gEKB3WWKZXmFDbGPQc5tFysm9xbgogo74YixUxZMTEBjZIIAYBEgTNwI+tor8FSFgSAB8nTB1ibImB+lyySgVp2fyhmiQ9psiZXDJToZJZ49Xykg5OUyKboe4JWZlOyzmGNCTzWNyGt5pQIPGjG0sOyjsCMb6dkZiyaaDE361nVpfAQ7oTLBBT7qxw55NyYYxJwEdZcaG/jDj92rZvqboof0i8N9OZNfXDX4YpUBprMMe7BW7ReaQgf8r2U+h/eeX93jOvg7ghJoCojYsvw8KAq8GmQA4JgD8+ILzeqmagu2XCOhuWIKScnDLOuKJaC6IlcEnJDDs+bz9d4Qy+WtqNLLOAd2TnOO+njiOOZLPFI8rYY7FtmFTZL6kXSLgS3wi2qaVcRwHLsV5yWNin8jn+Fgsi5SCjDWCT0hzclOfFQ+KZJE5gq8Fguazn7QBi5x+6xhpXgecyhAbOUM7WbBC5HGwIU4BATgwn8oB5QZVD9b5MPQJPwlXw6gh98dH8UB8IZJtZ1LiMuCrXhYrxg4olSH3ECXuEbeLOE7xovTAV0bxlnjylTUDNqkF5sgUAS6KvNN3ZM3XwB3JvSI2dYNqNiCXUv5qAhsyytgZZK4DfxSnJIO6vlySwrT2k88dxJmyY/cb86kesZ3/Ifgd+//QKEMOYCZa6d5xOd5ojlJBZMAca7F1APZhn5pqD3aYujxxPhS5HZSMrpr5pSe9fUVLWhdjJ6NaPi8uiNPigAjItJu1XzJz2GBbEo3Yl3XLxr+Yk+18ezbHlQAAAABJRU5ErkJggg==
---
Errors
--channels.info: method_not_supported_for_channel_type | color=red
```
-----
On a separate note, I am running this on a different Mac and I get this error when launching the GUI:

`Couldn't posix_spawn: error 1`
`launch path not accessible`

 This is usually indicative of some mismatch between the environment settings of the App and that of a regular terminal window. I ran into something similar to the `posix_spawn` error when I was writing a python plugin but never saw the second error before. Any advice on how to fix that?

**Comment by benjifs** [comment] 2019-07-10 21:36
I apologize. I thought I was doing a better job at printing errors. I just pushed a new update that should print out the error for the call as well as the object that its passing to the API. That should help us pinpoint where its failing. 

I also think I was mistaken in my previous message. I believe the call might be failing on `users.conversations` as the [documentation](https://api.slack.com/methods/users.conversations) for that call returns that error. Its confusing why that would be the case as that call has no reference to a channel but it is the only call that returns that error that I'm calling from the code. Hopefully the new error printing might help figure that out.

> On a separate note, I am running this on a different Mac and I get this error when launching the GUI:
> 
> `Couldn't posix_spawn: error 1`
> `launch path not accessible`

Is the plugin executable? Try running `chmod +x slack-team-notifications.1m.js` and see if that works. I got that from matryer/bitbar#189. Also, just in case `node` is installed somewhere else, see what `which node` returns. The script expects `/usr/local/bin/node` which I believe is the default but I could be wrong. What version of macOS are you running on that machine?

**Comment by frakman1** [comment] 2019-07-11 03:00
Ahh, it's complaining about a channel (CKFxxx ) that is marked as private but that I created and that token is used to post to (so I know I have access to that private channel) Not sure what to do about that. Perhaps you can recreate it by creating a private channel on your slack workspace.

```
Fetch conversation info for D6Cxxx
  /conversations.info (D6Cxxx)
ERROR: method_not_supported_for_channel_type
  channels.info
  {"token":"xoxp-xxx","channel":"CKFxxx","unreads":true}
! |color=red image=iVBORw0KG...==
---
Errors
--channels.info: method_not_supported_for_channel_type | color=red
```

Technically, it is the private channel that my slack app is installed into and for which I have a token that I am using with this script.

**Comment by benjifs** [comment] 2019-07-11 06:29
That's still very odd. I have a few private slack channels that I created and have joined and I'm not seeing that issue at all. Can you try getting the info for that channel and see what it returns? You should be able to call it from https://api.slack.com/methods/conversations.info/test with the channel id that you see after the error.

**Comment by frakman1** [comment] 2019-07-11 13:55
I went to that page, entered my token and that channel Id and it returned an OK with a bunch of channel information:


```
{
    "ok": true,
    "channel": {
        "id": "CKFxxxx",
        "name": "frakalerts",
        "is_channel": true,
        "is_group": false,
        "is_im": false,
        "created": 1560023740,
        "is_archived": false,
        "is_general": false,
        "unlinked": 0,
        "name_normalized": "frakalerts",
        "is_shared": false,
        "parent_conversation": null,
        "creator": "U6Cxxx",
        "is_ext_shared": false,
        "is_org_shared": false,
        "shared_team_ids": [
            "T04xxx"
        ],
        "pending_shared": [],
        "pending_connected_team_ids": [],
        "is_pending_ext_shared": false,
        "is_member": true,
        "is_private": true,
        "is_mpim": false,
        "last_read": "1562815739.045300",
        "is_open": true,
        "topic": {
            "value": "",
            "creator": "",
            "last_set": 0
        },
        "purpose": {
            "value": "",
            "creator": "",
            "last_set": 0
        }
    }
}
```

Why do you think the method is `conversation.info` when the error message in the `--debug` logs is pointing to the `channel.info` method:

```
ERROR: method_not_supported_for_channel_type
  channels.info      <-------------------------------------
```

I did the same test on the `https://api.slack.com/methods/channels.info/test` page and got the same `method_not_supported_for_channel_type` error:

![image](https://user-images.githubusercontent.com/5826484/61056781-f66f0f80-a3c1-11e9-8374-631d2078c99e.png)

UPDATE:
I guess you are going by the documentation that points to that error. Unfortunately, Slack's documentation is not always complete or consistent. I would go with the observable evidence at this point. I'll open a  help-desk ticket with Slack to request more information on this error.

**Comment by frakman1** [comment] 2019-07-11 14:43
I just tried the `channels.info` API test page on another private channel and get the same error. Apparently, it doesn't like private channels but works with other non-private channels.

**Comment by frakman1** [comment] 2019-07-11 15:48
_(Some feedback from Slack's help ticket)_

From the [channels.info documentation page/tab](https://api.slack.com/methods/channels.info):
```
This method returns information about a team channel.
To retrieve information on a private channel, use groups.info.
```

This particular channel is peculiar because it is private despite its ID starting with a `C`. This is because it was created as a public channel and then changed to private. I believe traditional private channels start with a `G`.

In any case, I would expect the code to give a similar error for regular private channels because `channels.info` method was only meant for public channels.

It seems like the new way to get information is via the conversations api according to [this](https://api.slack.com/docs/conversations-api) page


Channel Type | Previously used method | New method you should use
-- | -- | --
Public | channels.list | conversations.list
Private | groups.list | conversations.list
DM | im.list | conversations.list
Group DM | mpim.list | conversations.list

**Comment by benjifs** [comment] 2019-07-11 16:37
Thanks for all the info. The channel info that you posted was helpful because I was able to compare it to my private channels and came up to the same conclusion as you. My channels were created as private channels so `is_group = true`, `is_channel = false`, and `is_private = true`. In order to replicate it I created a new public channel and then changed it to private. The channel info now has `is_group = false`, `is_channel = true`, and `is_private = true`.

For that specific channel, if we call `channels.info` or `groups.info` we get error responses. If we then call `conversations.info` we do get the response except there is no `unread_count`.

I submitted bug reports to Slack for both of those issues so hopefully they'll work on fixing that at some point. I think I found a way around it though but I need to change the calls that are being made. Will update you on this soon.

**Comment by benjifs** [comment] 2019-07-11 21:03
New update. I had to rework some stuff in order to be able to show the unread count for that specific type of channel. The only thing that cannot be resolved right now is marking the channel as read. The `channels.mark` and `groups.mark` wont work for this type of channel as it returns `method_not_supported_for_channel_type`.

I was able to find an undocumented `conversations.mark` API call, however it seems at this time only `xoxs-` tokens can use it as I get a `not_allowed_token_type` error when calling that. If that call is made public then I should be able to change this so that all conversations can be marked as read but for now we wait.

Let me know if you have any issues with the new API calls. I didnt have to change any of the permissions for the Slack App but that might be the only thing that could give us issues as the documentation is all over the place.

Thanks for all your help identifying and debugging this issue.

**Comment by frakman1** [comment] 2019-07-11 23:44
No problem. Thanks for the updates. I'll try it and report back.
What type of token is the `xoxs-` token? I don't see it [here](https://api.slack.com/docs/token-types)

**Comment by frakman1** [comment] 2019-07-11 23:56
I'm getting a ton of `Too Many Requests` errors I didn't used to before.
I am also seeing this error: `ERROR: missing_scope` for `conversations.history` which acocrding to the [docs](https://api.slack.com/methods/conversations.history), means that I have to enable all of these scopes:
`channels:history  groups:history  im:history  mpim:history `
... which means I have to re-request permission to have more scope added to my app from the admins (sigh)

**Comment by benjifs** [comment] 2019-07-12 04:48
> What type of token is the `xoxs-` token? I don't see it [here](https://api.slack.com/docs/token-types)

Its undocumented but I found it while checking how the Slack.app was handling the "mark as read" for that type of channel which is also how I found the `conversations.mark` API call. It is only used by the official Slack apps.

> I'm getting a ton of `Too Many Requests` errors I didn't used to before.

I was afraid of this. Because `conversations.info` is [Tier 3 rate limited](https://api.slack.com/docs/rate-limits), it only allows around 50 calls to it. It was working before as that call was split between `channels.info`, `groups.info`, and `im.info`. I could revert back to those calls or I could check when that error occurs and simply stop making more requests. The problem in either situation is that assume you have 50+ channels, 50+ groups, and 50+ IMs, you would exceed the rate limits either way but at least it gives you more calls than just grouping them all into `conversations.info`. What do you suggest?

> I am also seeing this error: `ERROR: missing_scope` for `conversations.history` which acocrding to the [docs](https://api.slack.com/methods/conversations.history), means that I have to enable all of these scopes:
> `channels:history groups:history im:history mpim:history `
> ... which means I have to re-request permission to have more scope added to my app from the admins (sigh)

I thought that would be the case but I was surprised its not complaining for me for the same thing considering that I'm also making calls to `conversations.history`. Sorry about the inconvenience.

**Comment by frakman1** [comment] 2019-07-12 15:00
Why couldn't the original implementation call the appropriate `.info` for the respective channel? Is that possible or do you need to call `.info` just to know if a channel is private or not (which would be a catch 22)?

**Comment by benjifs** [comment] 2019-07-12 17:26
I added some debugging stuff on to see how many calls I'm making for the tokens that I use. Here is the output.
```
{
  "xoxp-token-1": {
    "team.info": 1,
    "conversations.list": 1,
    "conversations.info": 13,
    "conversations.history": 9,
    "users.info": 1
  },
  "xoxp-token-2": {
    "team.info": 1,
    "conversations.list": 1,
    "conversations.info": 37,
    "conversations.history": 21,
    "users.info": 1
  }
}
```
Because the new API docs suggest calling `conversations.info`, I made the change to that as opposed to `channels.info` or `groups.info`. By making the switch back to what it used to be you can see how those calls are split up and can handle some of those rate limits.
```
{
  "xoxp-token-1": {
    "team.info": 1,
    "conversations.list": 1,
    "channels.info": 7,
    "conversations.info": 5,
    "groups.info": 1,
    "conversations.history": 1,
    "users.info": 2
  },
  "xoxp-token-2": {
    "team.info": 1,
    "conversations.list": 1,
    "channels.info": 10,
    "conversations.info": 17,
    "groups.info": 7,
    "conversations.history": 1,
    "users.info": 1
  }
}
```
The other benefit to calling it separately rather than just `conversations.info` is that `channels.info` and `groups.info` seem to return the `unread_count` which also means one less call to `conversations.history`.

Technically we don't even need to call `conversations.info` but we still need to call `conversations.history` to get the unread count which would still be the same number of calls.

I think the best approach is just to switch the `conversations.info` call back to `channels.info` or `groups.info` since those endpoints are still available to use. This still would present a problem if you have 50+ channels that you are a part of in you Slack team and other than limiting it from my end how many calls are being made, there doesnt seem to be a good way around this.

**Comment by frakman1** [comment] 2019-07-12 17:46
I have far less than 50+ channels. 
I have about 14 channels and 10 chats open up at a time. Hopefully, I should be below the rate limit.

**Comment by benjifs** [comment] 2019-07-12 19:32
Do you get it all the time or only if you call the script multiple times? Technically it should be ok if you have less than 50 conversations (public channels, private channels, and IMs). However If you call the script multiple times in less than 1 minute you will get the `too many requests` error.

**Comment by frakman1** [comment] 2019-07-12 20:57
The script updates once a minute and those errors always shows up on the menubar. It's probably a good idea to change the cadence to once every 2 minutes or more (i.e. `slack-team-notifications.2m.js`)


I guess it's a moot point until I resolve the missing scope errors for `conversations.history`. I'll report back once I have those in place.

**Comment by frakman1** [comment] 2019-07-15 17:41
I got permissions added and reduced the update frequency. I still get `Too Many Requests` when set to 2 minutes, but seems to be OK with 5 minutes.

The only problem is that the private channel that was once public is not registering any updates via the plugin. i.e. I get a message with my name mentioned on that channel and the slack web page's tab in the browser has a `*` indicating activity but the plugin is silent with no entries.

**Comment by benjifs** [comment] 2019-07-15 17:57
I'm still not sure why I'm able to run the plugin without those permissions. I created an app that has the previous permission and its still working well for me now.

I also just pushed an update that at keeps count of how many calls are being made if you run it with `--debug` in the terminal. Should help figure out the rate limits and figure out where its happening. I also found a way to reduce some calls. Its not a lot in my case but it cut it down from 34 to 27 calls to `conversations.info`.

As an update to the tickets I submit to Slack, they're telling me that they're working on updating some of the documentation now but the inconsistency in the data that is returned is by design. I still haven't heard back about opening up `conversations.mark` for users so it's still impossible to mark as read a private channel that was previously public.

**Comment by frakman1** [comment] 2019-07-15 18:56
Looking at the debug logs, it looks like `conversations.info` which is being rate-limited is called for EVERY single channel in the workplace. I only actively have about 12 channels open that I even know about in the left frame of the slack web-page. Is there anyway for it to only query those ones?

**Comment by frakman1** [comment] 2019-07-15 19:14
I just checked the plugin again and I also don't get direct messages printing out (even when there are no Rate Limiting Errors)

**Comment by benjifs** [comment] 2019-07-15 19:47
```
{
  "ok": true,
  "channels": [
    {
      "//": "Public channel",
      "id": "Cxxxxxxx",
      "is_channel": true,
      "is_group": false,
      "is_im": false,
      "is_archived": false,
      "is_member": true,
      "is_private": false,
      "is_mpim": false
    },
    {
      "//": "Private channel that used to be public",
      "id": "Cxxxxxxxx",
      "is_channel": true,
      "is_group": false,
      "is_im": false,
      "is_archived": false,
      "is_member": true,
      "is_private": true,
      "is_mpim": false
    },
    {
      "//": "Public channel. Not a member",
      "id": "Cxxxxxx",
      "is_channel": true,
      "is_group": false,
      "is_im": false,
      "created": 1436365217,
      "is_archived": false,
      "is_member": false,
      "is_private": false,
      "is_mpim": false
    },
    {
      "//": "Private channel. Not open",
      "id": "Gxxxxxxxxx",
      "is_channel": false,
      "is_group": true,
      "is_im": false,
      "is_archived": false,
      "is_general": false,
      "is_member": true,
      "is_private": true,
      "is_mpim": true,
      "last_read": "1468511345.000005",
      "is_open": false
    },
    {
      "id": "Dxxxxxxxxx",
      "is_im": true,
      "user": "Uxxxxxxx",
      "is_user_deleted": false
    }
  ]
}
```
This is a sample clean output from `conversations.list`. There are a few things that we can check here to prevent calling `conversations.info` for a specific channel. The following is copied from line 283 in the main code.
```
if (channel.is_im) {
    if (channel.is_user_deleted) {
        continue;
    }
} else if (channel.is_group && !channel.is_open) {
    continue;
} else if (channel.is_archived || !channel.is_member) {
    continue;
}
```
There is an `is_open` value however it only seems to return the value for groups. Even then I'm not confident it consistently marks stuff as open if you have them open on the app. The new things I added to prevent additional calls was to also check if `last_read` or `unread_count` were returned for that conversation. `last_read` is returned fairly inconsistently too and in my case it only shows up for groups.

I still think the best way to address the rate limit is to revert the `conversations.info` call and instead call `channels.info` and `groups.info` so that at the very least we have higher rates since it would be splitting the calls between those two.


> I just checked the plugin again and I also don't get diret messages printing out (even when there are no Rate Limiting Errors_

You're not seeing any direct messages at all? That's very odd. Any errors along with that or is it just not registering messages?

**Comment by frakman1** [comment] 2019-07-15 19:54
There are no  errors displayed when I see no direct messages. Just am empty pull down.

Question about membership. Since I am using a slack app token, how would it know if I was a member or not? That is related to my slack username which I didn't think the slack app was connected to. In the legacy token case, the token assumed a user's identity in which case looking for group membership would make sense. 

If this is true, then perhaps it would make sense to add a username entry to the tokens file for the script to use to determine if it is a member of a channel or not.

**Comment by frakman1** [comment] 2019-07-15 20:22
Hmm, I wasn't using the latest and greatest from Github. Can you put some version tracker at the top that I can check my version against please?

**Comment by benjifs** [comment] 2019-07-15 20:36
> Question about membership. Since I am using a slack app token, how would it know if I was a member or not? That is related to my slack username which I didn't think the slack app was connected to. In the legacy token case, the token assumed a user's identity in which case looking for group membership would make sense.

Unless I'm mistaken, the token should be tied to your user identity. The slack token you can see should be the token that is tied to your account. A way to test that would be to test out the [users.profile.get](https://api.slack.com/methods/users.profile.get/test) API with the token and if it returns your username, you're good.

Otherwise, to verify that the token you are using is correct try deleting the tokens from `.tokens.js` and then go to `slack-team-notifications.1m.js` and on line 25 you should see a `SLACK_CLIENT_ID` variable. You can add your app's client ID there and use the authentication flow from there. For this to work though your app should have a valid Redirect URI and after it redirects, it should make a call to `oauth.access`. For more information on how that works you can check the [Oauth 2.0 Documentation](https://api.slack.com/docs/oauth) and the [index.html](https://github.com/benjifs/bitbar-slack-team-notifications/blob/master/index.html) in this project as that is what is called from the Redirect URI in my Slack App.

You should also be able to use the client ID that is there but that would install the app I created for to your slack team. It doesn't do anything other than generate the token but just giving you a heads up for transparency. I think that might require permissions from your team to install too so this might be more of a headache but just putting it out there as an option.

**Comment by benjifs** [comment] 2019-07-15 20:37
> Hmm, I wasn't using the latest and greatest from Github. Can you put some version tracker at the top that I can check my version against please?

Sometimes I get too distracted and forget to update the version numbers. Just pushed `v1.0.4` and tagged it as well.

**Comment by frakman1** [comment] 2019-07-15 20:42
I tried that API test page but it doesn't return a username. It takes username as an input.
Anyway, just putting in my token gave me a missing scope error:
```
{
    "ok": false,
    "error": "missing_scope",
    "needed": "users.profile:read",
    "provided": "identify,bot,incoming-webhook,channels:history,groups:history,im:history,mpim:history,channels:read,groups:read,im:read,mpim:read,team:read,users:read,channels:write,groups:write,im:write"
} 
```

**Comment by frakman1** [comment] 2019-07-15 20:54
```the token should be tied to your user identity.```
I think this is only true for the legacy tokens. The new slack app tokens can't be tied to my account (can it?) because they are meant to be installed by anyone in their channel and it queries the API as an independant entity. I could be wrong but that's my inderstanding. _I'll get clarification from Slack via a help-desk ticket I have open with them._

Thank you for the other option but I don't have a valid OAuth redirect URL as I am not doing any of that. I know the token is correct because it worked briefly with your original code before giving an error on that one channel (i.e. I did see unread messages at one point)

I was wondering what that `SLACK_CLIENT_ID` was for in the code. Should I have put my app's client ID in there from the beginning? Perhaps that field should be in the `tokens.js` file

**Comment by frakman1** [comment] 2019-07-15 22:00
I guess I was wrong. 

``` 
User access tokens (starts with xoxp) and are linked to the user who installed/authorized the app.
```
Also, from Slack HelpDesk:

```
you need to have a Slack API app with the following scopes that can call the 
users.conversations API method:

channels:read
groups:read
im:read
mpim:read
That API method would return the channels that the calling token owner is a part of.
```

**Comment by benjifs** [comment] 2019-07-15 22:05
So I'm not sure why you're seeing that but just to test I created a new slack team on a private window. I then created a new app as described in the [README.md](https://github.com/benjifs/bitbar-slack-team-notifications/blob/master/README.md).
Since a Redirect URI is needed, I added an invalid one so that I can authenticate everything manually myself. Once the Slack App was ready (no need to distribute in this case since its only intended for this test), I navigated to `https://slack.com/oauth/authorize?client_id={CLIENT_ID}&scope=client` with this apps client_id. After approving, it redirects to a page and in the URL you'll see it says: `https://REDIRECT_URI/?code={CODE}`. I then copied that code and made a POST request to generate the token:
```
https://slack.com/api/oauth.access?client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&code={CODE}
```
If all goes well, that call will generate the following response:
```
{
  "ok": true,
  "access_token": "xoxp-xxxxx",
  "scope": "read,client,identify,post",
  "user_id": "ULXXXXX",
  "team_name": "xxxxtest",
  "team_id": "TLxxxxxx"
}
```
That's the access token that you want

**Comment by benjifs** [comment] 2019-07-15 22:07
> Also, from Slack HelpDesk:
> 
> ```
> you need to have a Slack API app with the following scopes that can call the 
> users.conversations API method:
> 
> channels:read
> groups:read
> im:read
> mpim:read
> That API method would return the channels that the calling token owner is a part of.
> ```

I was previously using `users.conversations` but changed it to `conversations.list` and parsed some of the list myself. I think that was done during the debugging of the original issue. Since both methods are part of the Conversations API, I'll change to `users.conversations` to reduce the amount of conversations it returns.

**Comment by benjifs** [comment] 2019-07-15 22:25
In more disappointing news, it seems like even the `unread_count_display` is not correctly supported. This might be why sometimes you are not seeing notifications that you know are there. This means that I'm going to have to count the amount of items in `conversations.history` and remove items that arent relevant in order to display a proper count. This happened while testing in the new team I created but I can't see it at all in my other teams.

While digging around the app some more I found that Slack has a `client.counts` that would return the number of unread mentions. The problem again is that its limited to the `xoxs-` type token again so its not available for us to use. Might push another update tomorrow to see if I can handle the unread count better

**Comment by frakman1** [comment] 2019-07-15 22:31
When I go to `https://slack.com/oauth/authorize?client_id={CLIENT_ID}&scope=client`, it redirect to my company's oath page that makes me "Submit Request" to authorize the app like it was a new one or something. I don't want to submit this to the admins any more than I need to. This is where I stopped.

`After approving, it redirects to a page and in the URL you'll see it says`

It sounds like your experience is different than mine. Almost like you get to approve it yourself and move on to the next screen. Since I didn't click on "Submit Request" I don't know if there is a next page that gives me a `code` value to use to get a token. Anyway, thank you for the steps. I might use it in a different workspace that isn't administered so tightly.

**Comment by benjifs** [comment] 2019-07-17 20:11
Do you think we should try this on a testing Slack team? I can create one and add you as an admin so that you can try this authentication flow on there before you request it on your actual teams.

The other option like I mentioned before is if you have the `client_id` and `client_secret` for the app thats installed in your team, you can then generate the slack token by changing the `CLIENT_ID` variable in `slack-team-notifications.1m.js` and once it redirects to the URL, you should see in the address bar `?code={CODE}` where you can then make a POST request to `oauth.access` by running the following in your terminal.

```
 curl -X POST "https://slack.com/api/oauth.access?client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&code={CODE}"
```

**Comment by frakman1** [comment] 2019-07-18 18:04
Not a bad idea (creating a test Slack Team. Let's call it the A-Team haha). 

I was using your latest code `v1.0.5` and it seemed to list my unread alerts correctly. There was an unread message on my channel that was once public and then changed to private but that selecting `Mark as read` didn't make any difference. Later I saw that I had unread messages from someone and that `Mark as read` did actually work this time.

Not sure why that channel is different.

**Comment by benjifs** [comment] 2019-07-18 18:53
I just sent you an invite. Feel free to join and try running the OAuth flow for the plugin. You dont even need to change the `client_id` to just test it out right now since it should work with the default `client_id`.

`Mark as read` does not work for private channels that were public before. I have a ticket open with Slack about this so hopefully they get around to fixing that soon.

**Comment by benjifs** [comment] 2019-09-04 19:17
Coming back to this after a while. I'm closing this issue as last I heard it was working for you and the other issues were resolved

**Closed as completed by benjifs** 2019-09-04 19:17 UTC
